create table if not exists public.store_materials (
 id bigint generated by default as identity primary key,
 name text not null, category text not null default 'วัตถุดิบหลัก',
 stock numeric(14,3) not null default 0 check (stock >= 0),
 price numeric(14,2) not null default 0 check (price >= 0),
 unit text not null default 'kg', is_active boolean not null default true,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.store_recipes (
 id bigint generated by default as identity primary key, name text not null,
 product_id bigint references public.store_products(product_id) on delete set null,
 yield_kg numeric(14,3) not null check (yield_kg > 0), is_active boolean not null default true,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.store_recipe_items (
 id bigint generated by default as identity primary key,
 recipe_id bigint not null references public.store_recipes(id) on delete cascade,
 material_id bigint not null references public.store_materials(id) on delete restrict,
 quantity_kg numeric(14,3) not null check (quantity_kg > 0),
 material_price numeric(14,2) not null default 0 check (material_price >= 0),
 unique(recipe_id, material_id)
);
create table if not exists public.store_production_runs (
 id bigint generated by default as identity primary key,
 recipe_id bigint references public.store_recipes(id) on delete set null,
 production_date date not null default current_date,
 batch_count integer not null check (batch_count > 0),
 output_kg numeric(14,3) not null check (output_kg >= 0),
 material_cost numeric(14,2) not null default 0 check (material_cost >= 0),
 batch_code text, created_at timestamptz not null default now()
);
create table if not exists public.store_expenses (
 id bigint generated by default as identity primary key,
 expense_date date not null default current_date, category text not null default 'ทั่วไป',
 detail text not null default '', amount numeric(14,2) not null check (amount >= 0),
 created_at timestamptz not null default now()
);
alter table public.store_materials enable row level security;
alter table public.store_recipes enable row level security;
alter table public.store_recipe_items enable row level security;
alter table public.store_production_runs enable row level security;
alter table public.store_expenses enable row level security;
create policy store_materials_admin_all on public.store_materials for all to authenticated using ((select private.is_admin())) with check ((select private.is_admin()));
create policy store_recipes_admin_all on public.store_recipes for all to authenticated using ((select private.is_admin())) with check ((select private.is_admin()));
create policy store_recipe_items_admin_all on public.store_recipe_items for all to authenticated using ((select private.is_admin())) with check ((select private.is_admin()));
create policy store_production_runs_admin_all on public.store_production_runs for all to authenticated using ((select private.is_admin())) with check ((select private.is_admin()));
create policy store_expenses_admin_all on public.store_expenses for all to authenticated using ((select private.is_admin())) with check ((select private.is_admin()));
